using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Xml;

namespace Virtuart4DNavisworks
{
    /// <summary>
    /// Reformulated UI for writing custom attributes and sets to Navisworks model elements.
    /// Integrates with UITheme and swaps layout (Attributes on Left, Sets on Right).
    /// </summary>
    public class WriteAttributeForm : Form
    {
        private const string CATEGORIA_FIXA = VirtuartSchema.CategoriaPrincipal;

        public class SetResumo
        {
            public string Nome { get; }
            public int ItensSelecionados { get; }

            public SetResumo(string nome, int itensSelecionados)
            {
                Nome = nome;
                ItensSelecionados = itensSelecionados;
            }
        }

        // ── Controls ──────────────────────────────────────────────────
        private Panel pnlHeader;
        private Panel pnlEsquerdo; // Custom Attributes
        private Panel pnlDireito;  // Model Sets
        private TextBox txtPesquisa;
        private ListView lvCategorias;
        private TextBox txtCategoria;
        private DataGridView grid;
        private Label lblSubHeader;
        private Label lblResumoSets;
        private Label lblSelecaoSets;

        // ── Data ──────────────────────────────────────────────────────
        private readonly List<SetResumo> _setsExistentes;
        private readonly HashSet<string> _setsSelecionados;
        private readonly int _qtdSelecionados;
        private bool _atualizandoListaSets;
        private string _nomeSetDetectado;

        public string NomeCategoria { get; private set; }
        public List<AtributoCustom> Atributos { get; private set; }
        public List<string> NomesSetsSelecionados { get; private set; }
        public bool SolicitarExclusao { get; private set; }

        public WriteAttributeForm(int qtdSelecionados, List<SetResumo> setsExistentes,
            string nomeSetDetectado = null,
            IEnumerable<string> setsInicialmenteSelecionados = null)
        {
            Atributos = new List<AtributoCustom>();
            _setsExistentes = setsExistentes ?? new List<SetResumo>();
            
            var selecaoInicial = (setsInicialmenteSelecionados ?? Enumerable.Empty<string>())
                .Where(nome => !string.IsNullOrWhiteSpace(nome))
                .Select(nome => nome.Trim())
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            _setsSelecionados = selecaoInicial.Count > 0
                ? new HashSet<string>(selecaoInicial, StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>(
                    _setsExistentes
                        .Where(s => !string.IsNullOrWhiteSpace(s?.Nome))
                        .Select(s => s.Nome),
                    StringComparer.OrdinalIgnoreCase);

            NomesSetsSelecionados = new List<string>();
            _qtdSelecionados = qtdSelecionados;
            _nomeSetDetectado = nomeSetDetectado;

            SetStyle(ControlStyles.OptimizedDoubleBuffer | ControlStyles.AllPaintingInWmPaint, true);
            MontarLayout();
        }

        private void MontarLayout()
        {
            Text = "Virtuart4D - Write Attribute";
            Size = new Size(980, 640);
            MinimumSize = new Size(860, 520);
            StartPosition = FormStartPosition.CenterScreen;
            BackColor = UITheme.Color.Background;
            Font = UITheme.Typography.Body;

            // ── Header ─────────────────────────────────────────────────
            pnlHeader = UITheme.CreateHeader("Write Attribute", "Save custom properties and selected set names to model elements");
            pnlHeader.Height = 100;

            // Reposition the subtitle label generated by UITheme to avoid overlap
            foreach (Control ctrl in pnlHeader.Controls)
            {
                if (ctrl is Label lbl && lbl.Location.Y == 54)
                {
                    lbl.Location = new Point(24, 46);
                }
            }
            
            // SubHeader details in header
            lblSubHeader = new Label
            {
                Font = UITheme.Typography.BodySmall,
                ForeColor = Color.FromArgb(200, 240, 245),
                AutoSize = true,
                Location = new Point(24, 70),
                BackColor = Color.Transparent
            };
            pnlHeader.Controls.Add(lblSubHeader);
            Controls.Add(pnlHeader);

            // ── Footer ─────────────────────────────────────────────────
            var pnlFooter = UITheme.CreateFooter();

            // Cancel Button
            var btnCancelar = UITheme.CreateSecondaryButton("Cancel");
            btnCancelar.DialogResult = DialogResult.Cancel;
            btnCancelar.Width = 100;
            btnCancelar.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            btnCancelar.Location = new Point(pnlFooter.Width - 232, 8);
            pnlFooter.Controls.Add(btnCancelar);

            // Save Button
            var btnGravar = UITheme.CreatePrimaryButton("Save");
            btnGravar.Font = UITheme.Typography.Label;
            btnGravar.Width = 100;
            btnGravar.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            btnGravar.Location = new Point(pnlFooter.Width - 120, 8);
            btnGravar.Click += BtnGravar_Click;
            pnlFooter.Controls.Add(btnGravar);

            // Delete Created Button (Danger style)
            var btnExcluir = new Button
            {
                Text = "Delete Attributes",
                Font = UITheme.Typography.Label,
                ForeColor = Color.White,
                BackColor = UITheme.Color.Error,
                FlatStyle = FlatStyle.Flat,
                Height = 36,
                Width = 150,
                Cursor = Cursors.Hand,
                TextAlign = ContentAlignment.MiddleCenter,
                Anchor = AnchorStyles.Left | AnchorStyles.Bottom,
                Location = new Point(16, 8)
            };
            btnExcluir.FlatAppearance.BorderSize = 0;
            btnExcluir.MouseEnter += (s, e) => btnExcluir.BackColor = UITheme.Color.ErrorHover;
            btnExcluir.MouseLeave += (s, e) => btnExcluir.BackColor = UITheme.Color.Error;
            btnExcluir.Click += BtnExcluir_Click;
            pnlFooter.Controls.Add(btnExcluir);

            // Reposition controls on footer resize
            pnlFooter.Resize += (s, e) =>
            {
                btnGravar.Location = new Point(pnlFooter.Width - 120, 8);
                btnCancelar.Location = new Point(pnlFooter.Width - 232, 8);
            };

            Controls.Add(pnlFooter);

            // ── Main Content Container ─────────────────────────────────
            var pnlBody = new Panel
            {
                Dock = DockStyle.Fill,
                Padding = new Padding(16, 12, 16, 12)
            };
            Controls.Add(pnlBody);
            pnlBody.BringToFront();

            // ── Splitter: Custom Attributes on Left (60%), Sets on Right (40%) ─
            var splitter = new SplitContainer
            {
                Dock = DockStyle.Fill,
                SplitterWidth = 12,
                BackColor = UITheme.Color.Background,
                BorderStyle = BorderStyle.None
            };
            splitter.Panel1.BackColor = UITheme.Color.Background;
            splitter.Panel2.BackColor = UITheme.Color.Background;
            pnlBody.Controls.Add(splitter);

            // Set initial 60/40 split ratio
            splitter.SplitterDistance = (int)(splitter.Width * 0.58);
            pnlBody.Resize += (s, e) => splitter.SplitterDistance = (int)(splitter.Width * 0.58);

            MontarPainelAtributos(splitter.Panel1);
            MontarPainelSets(splitter.Panel2);

            AtualizarResumoSetsUI();

            AcceptButton = btnGravar;
            CancelButton = btnCancelar;
        }

        // ────────────────────────────────────────────────────────────────
        //  LEFT PANEL — Custom Attributes (60% Width)
        // ────────────────────────────────────────────────────────────────
        private void MontarPainelAtributos(Control parent)
        {
            pnlEsquerdo = UITheme.CreateCard();
            pnlEsquerdo.Dock = DockStyle.Fill;
            pnlEsquerdo.Padding = new Padding(16);
            parent.Controls.Add(pnlEsquerdo);

            // Title
            var lblTitulo = new Label
            {
                Text = "Custom Attributes Grid",
                Font = UITheme.Typography.H3,
                ForeColor = UITheme.Color.Primary,
                Dock = DockStyle.Top,
                Height = 24
            };
            pnlEsquerdo.Controls.Add(lblTitulo);

            // Category configuration line
            var pnlCat = new Panel
            {
                Dock = DockStyle.Top,
                Height = 36,
                Padding = new Padding(0, 4, 0, 4)
            };

            var lblCat = new Label
            {
                Text = "Storage Category:",
                Font = UITheme.Typography.Label,
                ForeColor = UITheme.Color.TextPrimary,
                AutoSize = true,
                Location = new Point(0, 8)
            };
            pnlCat.Controls.Add(lblCat);

            int catLabelW = TextRenderer.MeasureText("Storage Category:", UITheme.Typography.Label).Width + 8;

            txtCategoria = new TextBox
            {
                Text = CATEGORIA_FIXA,
                Font = UITheme.Typography.Body,
                BorderStyle = BorderStyle.FixedSingle,
                ReadOnly = true,
                BackColor = UITheme.Color.BackgroundSecondary,
                ForeColor = UITheme.Color.TextSecondary,
                Anchor = AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Top,
                Location = new Point(catLabelW, 4),
                Size = new Size(pnlCat.Width - catLabelW - 80, 26)
            };
            pnlCat.Controls.Add(txtCategoria);

            var btnResetCat = UITheme.CreateSecondaryButton("Reset");
            btnResetCat.Font = UITheme.Typography.BodySmall;
            btnResetCat.Height = 26;
            btnResetCat.Width = 70;
            btnResetCat.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            btnResetCat.Location = new Point(pnlCat.Width - 72, 4);
            btnResetCat.Click += (s, e) =>
            {
                txtCategoria.Text = CATEGORIA_FIXA;
                SolicitarExclusao = false;
                grid.Rows.Clear();
                AdicionarLinhaGrid("", "", "string");
                grid.Focus();
            };
            pnlCat.Controls.Add(btnResetCat);

            pnlCat.Resize += (s, e) =>
            {
                txtCategoria.Width = pnlCat.Width - catLabelW - 80;
                btnResetCat.Location = new Point(pnlCat.Width - 72, 4);
            };

            pnlEsquerdo.Controls.Add(pnlCat);
            pnlCat.BringToFront();

            // Help info box
            var pnlAjuda = new Panel
            {
                Dock = DockStyle.Top,
                Height = 46,
                BackColor = UITheme.Color.PrimaryVeryLight,
                Padding = new Padding(10, 6, 10, 6),
                Margin = new Padding(0, 4, 0, 8)
            };
            pnlAjuda.Paint += (s, e) =>
            {
                var rect = new Rectangle(0, 0, pnlAjuda.Width - 1, pnlAjuda.Height - 1);
                using (var pen = new Pen(UITheme.Color.PrimaryLight))
                    e.Graphics.DrawRectangle(pen, rect);
            };

            var lblAjuda = new Label
            {
                Dock = DockStyle.Fill,
                Font = UITheme.Typography.BodySmall,
                ForeColor = UITheme.Color.PrimaryHover,
                Text = $"Custom attributes entered below are written under '{CATEGORIA_FIXA}'. Names of selected sets are stored in the '{VirtuartSchema.PropriedadeSets}' property."
            };
            pnlAjuda.Controls.Add(lblAjuda);
            pnlEsquerdo.Controls.Add(pnlAjuda);
            pnlAjuda.BringToFront();

            // Spacer
            var spacer = new Panel { Dock = DockStyle.Top, Height = 8 };
            pnlEsquerdo.Controls.Add(spacer);
            spacer.BringToFront();

            // Action Buttons Bar above grid
            var pnlBtns = new Panel
            {
                Dock = DockStyle.Top,
                Height = 36,
                Padding = new Padding(0, 2, 0, 4)
            };

            var btnAdd = UITheme.CreatePrimaryButton("+ Add Row");
            btnAdd.Font = UITheme.Typography.BodySmall;
            btnAdd.Height = 28;
            btnAdd.Width = 95;
            btnAdd.Location = new Point(0, 2);
            btnAdd.Click += (s, e) => AdicionarLinhaGrid("", "", "string");
            pnlBtns.Controls.Add(btnAdd);

            var btnRemove = new Button
            {
                Text = "- Remove",
                Font = UITheme.Typography.BodySmall,
                ForeColor = UITheme.Color.Error,
                BackColor = Color.White,
                FlatStyle = FlatStyle.Flat,
                Height = 28,
                Width = 85,
                Cursor = Cursors.Hand,
                Location = new Point(100, 2)
            };
            btnRemove.FlatAppearance.BorderColor = UITheme.Color.Error;
            btnRemove.MouseEnter += (s, e) => btnRemove.BackColor = UITheme.Color.ErrorLight;
            btnRemove.MouseLeave += (s, e) => btnRemove.BackColor = Color.White;
            btnRemove.Click += (s, e) =>
            {
                if (grid.SelectedRows.Count > 0 && grid.Rows.Count > 0)
                    grid.Rows.RemoveAt(grid.SelectedRows[0].Index);
            };
            pnlBtns.Controls.Add(btnRemove);

            var btnLimpar = UITheme.CreateSecondaryButton("Clear Grid");
            btnLimpar.Font = UITheme.Typography.BodySmall;
            btnLimpar.Height = 28;
            btnLimpar.Width = 90;
            btnLimpar.Location = new Point(190, 2);
            btnLimpar.Click += (s, e) => grid.Rows.Clear();
            pnlBtns.Controls.Add(btnLimpar);

            var btnImportar = UITheme.CreateSecondaryButton("Import");
            btnImportar.Font = UITheme.Typography.BodySmall;
            btnImportar.Height = 28;
            btnImportar.Width = 75;
            btnImportar.Location = new Point(285, 2);
            btnImportar.Click += BtnImportar_Click;
            pnlBtns.Controls.Add(btnImportar);

            var btnExportar = UITheme.CreateSecondaryButton("Export");
            btnExportar.Font = UITheme.Typography.BodySmall;
            btnExportar.Height = 28;
            btnExportar.Width = 75;
            btnExportar.Location = new Point(365, 2);
            btnExportar.Click += BtnExportar_Click;
            pnlBtns.Controls.Add(btnExportar);

            pnlEsquerdo.Controls.Add(pnlBtns);
            pnlBtns.BringToFront();

            // Grid View
            grid = new DataGridView
            {
                Dock = DockStyle.Fill,
                RowHeadersVisible = false,
                SelectionMode = DataGridViewSelectionMode.FullRowSelect,
                AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill,
                RowTemplate = { Height = 30 },
                ColumnHeadersHeight = 34,
                ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing
            };
            UITheme.StyleDataGridView(grid);

            grid.Columns.Add(new DataGridViewTextBoxColumn
            {
                Name = "Nome",
                HeaderText = "Name",
                FillWeight = 40
            });

            grid.Columns.Add(new DataGridViewTextBoxColumn
            {
                Name = "Valor",
                HeaderText = "Value",
                FillWeight = 40
            });

            var colTipo = new DataGridViewComboBoxColumn
            {
                Name = "Tipo",
                HeaderText = "Type",
                FillWeight = 20,
                FlatStyle = FlatStyle.Flat,
                DisplayStyle = DataGridViewComboBoxDisplayStyle.DropDownButton
            };
            colTipo.Items.AddRange("string", "double", "int", "bool");
            grid.Columns.Add(colTipo);

            pnlEsquerdo.Controls.Add(grid);
            grid.BringToFront();

            // Add initial empty row
            AdicionarLinhaGrid("", "", "string");
        }

        private void AdicionarLinhaGrid(string nome, string valor, string tipo)
        {
            int idx = grid.Rows.Add();
            grid.Rows[idx].Cells["Nome"].Value = nome;
            grid.Rows[idx].Cells["Valor"].Value = valor;
            grid.Rows[idx].Cells["Tipo"].Value = tipo;
        }

        // ────────────────────────────────────────────────────────────────
        //  RIGHT PANEL — Model Sets (40% Width)
        // ────────────────────────────────────────────────────────────────
        private void MontarPainelSets(Control parent)
        {
            pnlDireito = UITheme.CreateCard();
            pnlDireito.Dock = DockStyle.Fill;
            pnlDireito.Padding = new Padding(16);
            parent.Controls.Add(pnlDireito);

            // Title
            var lblTitulo = new Label
            {
                Text = "Detected Model Sets",
                Font = UITheme.Typography.H3,
                ForeColor = UITheme.Color.Primary,
                Dock = DockStyle.Top,
                Height = 24
            };
            pnlDireito.Controls.Add(lblTitulo);

            // Small hint label
            var lblDica = new Label
            {
                Text = "Mark sets that should be assigned to this item",
                Font = UITheme.Typography.BodySmall,
                ForeColor = UITheme.Color.TextSecondary,
                Dock = DockStyle.Top,
                Height = 18
            };
            pnlDireito.Controls.Add(lblDica);
            lblDica.BringToFront();

            // Sets selection count box
            var pnlResumoSets = new Panel
            {
                Dock = DockStyle.Top,
                Height = 52,
                BackColor = UITheme.Color.BackgroundSecondary,
                Padding = new Padding(10, 6, 10, 6),
                Margin = new Padding(0, 4, 0, 6)
            };
            pnlResumoSets.Paint += (s, e) =>
            {
                var rect = new Rectangle(0, 0, pnlResumoSets.Width - 1, pnlResumoSets.Height - 1);
                using (var pen = new Pen(UITheme.Color.BorderLight))
                    e.Graphics.DrawRectangle(pen, rect);
            };

            lblResumoSets = new Label
            {
                Dock = DockStyle.Fill,
                Font = UITheme.Typography.BodySmall,
                ForeColor = UITheme.Color.TextPrimary,
                Text = ObterTextoResumoSets()
            };
            pnlResumoSets.Controls.Add(lblResumoSets);
            pnlDireito.Controls.Add(pnlResumoSets);
            pnlResumoSets.BringToFront();

            // Search Bar panel
            var pnlPesquisa = new Panel
            {
                Dock = DockStyle.Top,
                Height = 36,
                Padding = new Padding(0, 4, 0, 4)
            };

            txtPesquisa = new TextBox
            {
                Dock = DockStyle.Fill,
                Font = UITheme.Typography.Body,
                ForeColor = UITheme.Color.TextTertiary,
                Text = "Search sets...",
                BorderStyle = BorderStyle.FixedSingle
            };
            txtPesquisa.GotFocus += (s, e) =>
            {
                if (txtPesquisa.ForeColor == UITheme.Color.TextTertiary)
                {
                    txtPesquisa.Text = "";
                    txtPesquisa.ForeColor = UITheme.Color.TextPrimary;
                }
            };
            txtPesquisa.LostFocus += (s, e) =>
            {
                if (string.IsNullOrWhiteSpace(txtPesquisa.Text))
                {
                    txtPesquisa.Text = "Search sets...";
                    txtPesquisa.ForeColor = UITheme.Color.TextTertiary;
                }
            };
            txtPesquisa.TextChanged += (s, e) => PreencherSets();
            pnlPesquisa.Controls.Add(txtPesquisa);
            pnlDireito.Controls.Add(pnlPesquisa);
            pnlPesquisa.BringToFront();

            // Selection controls bar (Select All / Clear)
            var pnlSelecaoSets = new Panel
            {
                Dock = DockStyle.Top,
                Height = 34,
                Padding = new Padding(0, 4, 0, 2)
            };

            var btnLimparSets = UITheme.CreateSecondaryButton("Clear");
            btnLimparSets.Font = UITheme.Typography.BodySmall;
            btnLimparSets.Height = 26;
            btnLimparSets.Width = 66;
            btnLimparSets.Dock = DockStyle.Right;
            btnLimparSets.Click += (s, e) => DefinirSelecaoSets(false);
            pnlSelecaoSets.Controls.Add(btnLimparSets);

            var btnSelecionarTodos = UITheme.CreateSecondaryButton("Select All");
            btnSelecionarTodos.Font = UITheme.Typography.BodySmall;
            btnSelecionarTodos.Height = 26;
            btnSelecionarTodos.Width = 84;
            btnSelecionarTodos.Dock = DockStyle.Right;
            btnSelecionarTodos.Margin = new Padding(0, 0, 8, 0);
            btnSelecionarTodos.Click += (s, e) => DefinirSelecaoSets(true);
            pnlSelecaoSets.Controls.Add(btnSelecionarTodos);

            lblSelecaoSets = new Label
            {
                Dock = DockStyle.Fill,
                Font = UITheme.Typography.BodySmall,
                ForeColor = UITheme.Color.TextSecondary,
                TextAlign = ContentAlignment.MiddleLeft
            };
            pnlSelecaoSets.Controls.Add(lblSelecaoSets);

            pnlDireito.Controls.Add(pnlSelecaoSets);
            pnlSelecaoSets.BringToFront();

            // Sets ListView
            lvCategorias = new ListView
            {
                Dock = DockStyle.Fill,
                View = View.Details,
                FullRowSelect = true,
                CheckBoxes = true,
                HeaderStyle = ColumnHeaderStyle.Nonclickable,
                BorderStyle = BorderStyle.FixedSingle,
                Font = UITheme.Typography.BodySmall,
                GridLines = false,
                MultiSelect = false,
                ShowItemToolTips = true
            };
            lvCategorias.Columns.Add("Set Name", 240);
            lvCategorias.Columns.Add("Elements", 70, HorizontalAlignment.Center);
            lvCategorias.ItemChecked += LvCategorias_ItemChecked;

            pnlDireito.Controls.Add(lvCategorias);
            lvCategorias.BringToFront();

            PreencherSets();
        }

        private void PreencherSets()
        {
            _atualizandoListaSets = true;
            lvCategorias.Items.Clear();
            
            var filtro = "";
            if (txtPesquisa != null && txtPesquisa.ForeColor != UITheme.Color.TextTertiary)
                filtro = txtPesquisa.Text.Trim().ToLower();

            foreach (var setInfo in _setsExistentes.OrderBy(s => s.Nome))
            {
                if (!string.IsNullOrEmpty(filtro) && !setInfo.Nome.ToLower().Contains(filtro))
                    continue;

                var item = new ListViewItem(setInfo.Nome);
                item.SubItems.Add(setInfo.ItensSelecionados.ToString());
                item.Tag = setInfo.Nome;
                item.ToolTipText = $"{setInfo.ItensSelecionados} element(s) belong to this set.";
                item.Checked = _setsSelecionados.Contains(setInfo.Nome);

                lvCategorias.Items.Add(item);
            }

            if (lvCategorias.Columns.Count >= 2)
            {
                lvCategorias.Columns[0].Width = -2;
                lvCategorias.Columns[1].Width = 70;
            }

            _atualizandoListaSets = false;
            AtualizarResumoSetsUI();
        }

        private void LvCategorias_ItemChecked(object sender, ItemCheckedEventArgs e)
        {
            if (_atualizandoListaSets || !(e.Item.Tag is string nomeSet)) return;

            if (e.Item.Checked)
                _setsSelecionados.Add(nomeSet);
            else
                _setsSelecionados.Remove(nomeSet);

            AtualizarResumoSetsUI();
        }

        private void DefinirSelecaoSets(bool selecionarTodos)
        {
            if (selecionarTodos)
            {
                _setsSelecionados.Clear();
                foreach (var setInfo in _setsExistentes)
                {
                    if (!string.IsNullOrWhiteSpace(setInfo?.Nome))
                        _setsSelecionados.Add(setInfo.Nome);
                }
            }
            else
            {
                _setsSelecionados.Clear();
            }

            PreencherSets();
        }

        private void AtualizarResumoSetsUI()
        {
            if (lblSubHeader != null)
                lblSubHeader.Text = ObterTextoSubHeader();

            if (lblResumoSets != null)
                lblResumoSets.Text = ObterTextoResumoSets();

            if (lblSelecaoSets != null)
                lblSelecaoSets.Text = $"{_setsSelecionados.Count} selected";
        }

        private string ObterTextoResumoSets()
        {
            if (_setsExistentes.Count == 0)
                return "No sets were detected for the current selection. You can still save custom attributes.";

            return $"{_setsSelecionados.Count} of {_setsExistentes.Count} sets selected to be written into the '{VirtuartSchema.PropriedadeSets}' field.";
        }

        private string ObterTextoSubHeader()
        {
            int totalSets = _setsExistentes.Count;
            int totalSel = _setsSelecionados.Count;

            if (totalSets > 0 && !string.IsNullOrWhiteSpace(_nomeSetDetectado))
                return $"{_qtdSelecionados} element(s) | {totalSel}/{totalSets} sets selected | First: {_nomeSetDetectado}";
            if (totalSets > 0)
                return $"{_qtdSelecionados} element(s) | {totalSel}/{totalSets} sets selected";

            return $"{_qtdSelecionados} element(s) selected";
        }

        // ────────────────────────────────────────────────────────────────
        //  IMPORT / EXPORT FUNCTIONS
        // ────────────────────────────────────────────────────────────────
        private void BtnExportar_Click(object sender, EventArgs e)
        {
            if (grid.Rows.Count == 0)
            {
                MessageBox.Show("No attributes to export.", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            using (var dlg = new SaveFileDialog
            {
                Filter = "CSV (*.csv)|*.csv|XML (*.xml)|*.xml",
                Title = "Export Attributes",
                DefaultExt = "csv"
            })
            {
                if (dlg.ShowDialog() != DialogResult.OK) return;

                try
                {
                    if (dlg.FileName.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
                        ExportarXml(dlg.FileName);
                    else
                        ExportarCsv(dlg.FileName);

                    MessageBox.Show("Attributes exported successfully!", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error exporting: {ex.Message}", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        private void BtnImportar_Click(object sender, EventArgs e)
        {
            using (var dlg = new OpenFileDialog
            {
                Filter = "CSV (*.csv)|*.csv|XML (*.xml)|*.xml",
                Title = "Import Attributes"
            })
            {
                if (dlg.ShowDialog() != DialogResult.OK) return;

                try
                {
                    if (dlg.FileName.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
                        ImportarXml(dlg.FileName);
                    else
                        ImportarCsv(dlg.FileName);

                    MessageBox.Show($"Successfully imported {grid.Rows.Count} attribute(s).", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error importing file: {ex.Message}", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        private void ExportarCsv(string path)
        {
            var sb = new StringBuilder();
            sb.AppendLine("Category,Name,Value,Type");

            var cat = CATEGORIA_FIXA;
            for (int i = 0; i < grid.Rows.Count; i++)
            {
                var nome = Escapar(grid.Rows[i].Cells["Nome"].Value?.ToString() ?? "");
                var valor = Escapar(grid.Rows[i].Cells["Valor"].Value?.ToString() ?? "");
                var tipo = grid.Rows[i].Cells["Tipo"].Value?.ToString() ?? "string";
                sb.AppendLine($"{Escapar(cat)},{nome},{valor},{tipo}");
            }

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }

        private void ExportarXml(string path)
        {
            var ds = new DataSet("VirtuartAtributos");
            var dt = new DataTable("Atributo");
            dt.Columns.Add("Categoria", typeof(string));
            dt.Columns.Add("Nome", typeof(string));
            dt.Columns.Add("Valor", typeof(string));
            dt.Columns.Add("Tipo", typeof(string));

            var cat = CATEGORIA_FIXA;
            for (int i = 0; i < grid.Rows.Count; i++)
            {
                var row = dt.NewRow();
                row["Categoria"] = cat;
                row["Nome"] = grid.Rows[i].Cells["Nome"].Value?.ToString() ?? "";
                row["Valor"] = grid.Rows[i].Cells["Valor"].Value?.ToString() ?? "";
                row["Tipo"] = grid.Rows[i].Cells["Tipo"].Value?.ToString() ?? "string";
                dt.Rows.Add(row);
            }

            ds.Tables.Add(dt);
            var settings = new XmlWriterSettings { Indent = true };
            using (var writer = XmlWriter.Create(path, settings))
                ds.WriteXml(writer);
        }

        private void ImportarCsv(string path)
        {
            var lines = File.ReadAllLines(path, Encoding.UTF8);
            if (lines.Length < 2) return;

            grid.Rows.Clear();
            for (int i = 1; i < lines.Length; i++)
            {
                var parts = ParseCsvLine(lines[i]);
                if (parts.Count < 4) continue;

                AdicionarLinhaGrid(parts[1], parts[2], parts[3]);
            }
        }

        private void ImportarXml(string path)
        {
            var ds = new DataSet();
            ds.ReadXml(path);
            var dt = ds.Tables[0];

            grid.Rows.Clear();
            foreach (DataRow row in dt.Rows)
            {
                var nome = row.Table.Columns.Contains("Nome") ? row["Nome"].ToString() : "";
                var valor = row.Table.Columns.Contains("Valor") ? row["Valor"].ToString() : "";
                var tipo = row.Table.Columns.Contains("Tipo") ? row["Tipo"].ToString() : "string";

                AdicionarLinhaGrid(nome, valor, tipo);
            }
        }

        private static string Escapar(string val)
        {
            if (val.Contains(",") || val.Contains("\"") || val.Contains("\n"))
                return "\"" + val.Replace("\"", "\"\"") + "\"";
            return val;
        }

        private static List<string> ParseCsvLine(string line)
        {
            var result = new List<string>();
            bool inQuotes = false;
            var current = new StringBuilder();

            for (int i = 0; i < line.Length; i++)
            {
                char c = line[i];
                if (inQuotes)
                {
                    if (c == '"' && i + 1 < line.Length && line[i + 1] == '"')
                    { current.Append('"'); i++; }
                    else if (c == '"')
                        inQuotes = false;
                    else
                        current.Append(c);
                }
                else
                {
                    if (c == '"') inQuotes = true;
                    else if (c == ',') { result.Add(current.ToString()); current.Clear(); }
                    else current.Append(c);
                }
            }
            result.Add(current.ToString());
            return result;
        }

        // ────────────────────────────────────────────────────────────────
        //  SAVE / DELETE BUTTON ACTIONS
        // ────────────────────────────────────────────────────────────────
        private void BtnGravar_Click(object sender, EventArgs e)
        {
            NomeCategoria = CATEGORIA_FIXA;
            SolicitarExclusao = false;
            NomesSetsSelecionados = _setsSelecionados
                .OrderBy(nome => nome, StringComparer.OrdinalIgnoreCase)
                .ToList();

            Atributos.Clear();

            for (int i = 0; i < grid.Rows.Count; i++)
            {
                var nome = grid.Rows[i].Cells["Nome"].Value?.ToString()?.Trim();
                var valor = grid.Rows[i].Cells["Valor"].Value?.ToString()?.Trim() ?? "";
                var tipo = grid.Rows[i].Cells["Tipo"].Value?.ToString() ?? "string";

                if (string.IsNullOrEmpty(nome)) continue;

                Atributos.Add(new AtributoCustom(NomeCategoria, nome, valor, tipo));
            }

            if (Atributos.Count == 0 && NomesSetsSelecionados.Count == 0)
            {
                MessageBox.Show("Please add at least one custom attribute or select a set before saving.", "Virtuart4D", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            DialogResult = DialogResult.OK;
            Close();
        }

        private void BtnExcluir_Click(object sender, EventArgs e)
        {
            var result = MessageBox.Show(
                $"Are you sure you want to delete all attributes created under '{CATEGORIA_FIXA}' and legacy categories from the selected elements?",
                "Virtuart4D - Delete Attributes",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning);

            if (result != DialogResult.Yes) return;

            NomeCategoria = CATEGORIA_FIXA;
            SolicitarExclusao = true;
            DialogResult = DialogResult.OK;
            Close();
        }
    }
}
